# Use root/toor as user/password credentials
version: '3.1'

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: devdb
        ports:
            - 3306:3306
            - 33060:33060
        volumes:
            - ../developmentDatabase/mysql/:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    
    strapi:
        image: strapi/strapi
        volumes:
            - ./:/srv/app
        restart: always
        environment:
            DATABASE_HOST: db
            DATABASE_PORT: 3306
            DATABASE_NAME: devdb
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: toor
        ports: 
            - 1337:1337
            